/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/final5.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../contexts/customization";

const Shirt = (props) => {
  const { ShirtColor } = useCustomization();
  const { nodes, materials } = useGLTF("./models/final5.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BROCKCREATIVE_SHIRT.geometry}
        material={materials.lambert1}
        position={[0, 0.06, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow
      >
        <meshStandardMaterial color={ShirtColor.color} />
      </mesh>
    </group>
  );
};

useGLTF.preload("./models/final5.gltf");

export default Shirt;
